pproject/p1app/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name='p1app'
urlpatterns = [
    path('register',views.register,name='register'),
    path('login', views.login, name='login'),
    path('logout',views.logout,name='logout')
]

urlpatterns += staticfiles_urlpatterns()

from django.conf import settings
from django.conf.urls.static import static

pproject/papp/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
app_name='papp'
from . import views
urlpatterns = [
    path('',views.fun,name='fun')

]
urlpatterns += staticfiles_urlpatterns()

from django.conf import settings
from django.conf.urls.static import static

pproject/pproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static


from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('papp/',include('papp.urls')),
    path('p1app/',include('p1app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                   document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                   document_root=settings.MEDIA_ROOT)

pproject/p1app/models.py
from django.db import models

# Create your models here.

pproject/papp/models.py
from django.db import models

# Create your models here.
class place(models.Model):

    name=models.CharField(max_length=100)
    img=models.ImageField(upload_to='pics1')
    desc=models.TextField()
    #def __str__(self):
       # return self.name


from django.db import models

pproject/p1app/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User,auth
# Create your views here.
from django.contrib import messages,auth

def login(request):
     if request.method=='POST':
          username2=request.POST['username']
          password2=request.POST['password']
          user=auth.authenticate(username=username2,password=password2)
          if user is not None:
               auth.login(request,user)
               return redirect('/')
          else:
               message.info(request,"invalid credentials")
               return redirect('p1app:login')
     else:

          return render(request,"login.html")
def register(request):
   if request.method == 'POST':
        username1 = request.POST['username']
        firstname1 = request.POST['firstname']
        lastname1 = request.POST['lastname']
        email1 = request.POST['email']
        password1 = request.POST['password']
        cpassword1= request.POST['cpassword']
        if password1 == cpassword1 :
             if User.objects.filter(username=username1).exists():
                  messages.info(request, 'username already exist')
                  return redirect('p1app:register')
             else:
                  if User.objects.filter(email=email1).exists():
                       messages.info(request, 'Registration Failed - Try different email address')
                       return redirect('p1app:register')
                  else:


                       user = User.objects.create_user(password=password1,username=username1,first_name=firstname1,last_name=lastname1,email=email1)
                       user.save();

                       print("user created")
                       return redirect('p1app:login')
        else:
             messages.info(request, 'password dose not match')
             return redirect('p1app:register')
        return redirect('/')

   else:

        return render(request, "register.html")
def logout(request):
     auth.logout(request)
     return redirect('p1app:register')

pproject/papp/views.py
from django.shortcuts import render
from . models import place


from django.shortcuts import render

def fun(request):
    obj=place.objects.all()
    return render(request,"index.html",{'result':obj})

pproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   <script src="https://kit.fontawesome.com/23f0fda106.js" crossorigin="anonymous"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >



    {% block content %}

    {% endblock %}




<script src="{% static 'popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

pproject/templates/footer.html
<footer class="bg-light text-center text-lg-start mx-auto">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">travel.com</a>
  </div>
  <!-- Copyright -->
</footer>

pproject/templates/login.html
{% load static %}
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
<script src="https://kit.fontawesome.com/23f0fda106.js" crossorigin="anonymous"></script>
    <script src="{% static 'popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
<title> Login Page </title>
<style>
Body {
  font-family: Calibri, Helvetica, sans-serif;

}
button {
       background-color: #4CAF50;
       width: 100%;
        color: orange;
        padding: 15px;
        margin: 10px 0px;
        border: none;
        cursor: pointer;
         }
 form {
        border: 3px solid #f1f1f1;
    }
 input[type=text], input[type=password] {
        width: 100%;
        margin: 8px 0;
        padding: 12px 20px;
        display: inline-block;
        border: 2px solid green;
        box-sizing: border-box;
    }
 button:hover {
        opacity: 0.7;
    }
  .cancelbtn {
        width: auto;
        padding: 10px 18px;
        margin: 10px 5px;
    }


 .container {
        padding: 25px;
        background-color: lightgreen;
    }
</style>
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="color:#ffffff">
  <div class="container-fluid" >

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


       <!-- <li class="nav-item dropdown {% if 'ecommerceapp:allprocat' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#"><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'papp:fun' %}" style="color:#ffffff;font-size:25px;">Home</a>
        </li>


          </ul>
    </div>

</nav>
<div>
<img class="my_image my_image_padding" src="{% static 'images/11.png' %}" alt="our products" style="width:1450px; height:350px">
</div>
<br>
    <center> <h1> Student Login Form </h1> </center>
    <form action="{% url 'papp:fun' %}" method="post">
        {% csrf_token %}
        <div class="container">
            <label>Username : </label>
            <input type="text" placeholder="Enter Username" name="username" required>
            <label>Password : </label>
            <input type="password" placeholder="Enter Password" name="password" required>
            <input type="submit" style="text-size:20px;color:red" name="submit" value="Login">
            <input type="checkbox" checked="checked"> Remember me
            <input type="submit" class="cancelbtn"> Cancel</input>
            Forgot <a href="#"> password? </a>
        </div>
    </form>

<div>
    {% for message in messages %}
    <h3 ALIGN="CENTER">{{message}}</h3>
    {% endfor %}
    </div>
{% endblock %}
    <div class="footer navbar-fixed-bottom my-footer mx-auto" style="background-color:black">
  <p class="text-center" style="color:white">@copy; Travel pvt limited</p>
</div>
</body>
</html>

pproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="color:#ffffff">
  <div class="container-fluid" >

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


       <!-- <li class="nav-item dropdown {% if 'ecommerceapp:allprocat' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#"><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="register.html" style="color:#000000;font-size:25px;">Home</a>
        </li>


          </ul>
    </div>

</nav>

pproject/templates/register.html
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
   <style>
    body{
  font-family: Calibri, Helvetica, sans-serif;

}
.container {
    padding: 50px;
  background-color: lightblue;
}

input[type=text], input[type=password],  input[type=email] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password], input[type=email]:focus {
  background-color: orange;
  outline: none;
}
 div {
            padding: 10px 0;
         }
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 20%;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}
</style>
    <title>form</title>
</head>
<body bgcolor="dark blue">
{% block content %}
<nav class="navbar navbar-expand-lg navbar-light bg-dark" style="color:#ffffff">
  <div class="container-fluid" >

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">


       <!-- <li class="nav-item dropdown {% if 'ecommerceapp:allprocat' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#"><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'papp:fun' %}" style="color:#ffffff;font-size:25px;">Home</a>
        </li>


          </ul>
    </div>

</nav>
<img class="my_image my_image_padding" src="{% static 'images/22.png' %}" alt="our products" style="width:1490px; height:350px">
</div>
<br>
<div class="space">
<form method="post" action="{% url 'p1app:register' %}" >

{% csrf_token %}
    <div class="container">
    <center><h1>REGISTRATION FORM</h1></center>
        <hr>

        <label>User name:</label><input type="text" name="username" placeholder="Enter your user name">
        <label>First Name:</label><input type="text" name="firstname" placeholder="Enter your first  name">
        <label>Last name:</label><input type="text" name="lastname" placeholder="Enter your last name">
        <label>Email:</label>
        <input type="email" name="email" placeholder="Enter your email">

      <br>  <label>Password:</label><input type="password" name="password" placeholder="Enter your password">

        <label>Confirmation password:</label><input type="password" name="cpassword" placeholder="Enter your confirmation password">
       <center>  <input type="submit" class="registerbtn" value="submit">
       </input></center>
    </div>
        </form></div>
<div>
{% for message in messages %}
<h3 ALIGN="CENTER">{{message}}</h3>
{% endfor %}
</div>
{% endblock %}
        <div class="footer navbar-fixed-bottom my-footer mx-auto" style="background-color:black">
  <p class="text-center" style="color:white">@copy; Travel pvt limited</p>
</div>
</body>
</html>